
SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG'

SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE DEPARTMENT_ID=90

1
SELECT COUNT(JOB_ID) FROM EMPLOYEES
2
SELECT SUM(SALARY) FROM EMPLOYEES
3
SELECT MIN(SALARY) FROM EMPLOYEES
4
SELECT MAX(SALARY) FROM EMPLOYEES HAVING JOB_ID = 'IT_PROG' GROUP BY JOB_ID

SELECT MAX(SALARY) FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG'
5
SELECT AVG(SALARY), COUNT(EMPLOYEE_ID) FROM EMPLOYEES WHERE DEPARTMENT_ID = 90
6
SELECT MAX(SALARY), MIN(SALARY), SUM(SALARY), AVG(SALARY) FROM EMPLOYEES
7
SELECT COUNT(EMPLOYEE_ID), JOB_ID FROM EMPLOYEES GROUP BY JOB_ID

8
SELECT MAX(SALARY) - MIN(SALARY) AS DIFFERENCE FROM EMPLOYEES;
9
SELECT MANAGER_ID, MIN(SALARY) FROM EMPLOYEES GROUP BY MANAGER_ID
10
SELECT DEPARTMENT_ID, SUM(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID
11
SELECT DEPARTMENT_ID, AVG(SALARY) COUNT * FROM EMPLOYES GROUP BY DEPARTMENT_ID HAVING COUNT(EMPLOYEE_ID)>10 
12
SELECT JOB_ID, MAX(SALARY) FROM EMPLOYEES HAVING MAX(SALARY)>=4000 GROUP BY JOB_ID
